#!/usr/bin/ruby

my_path = File.expand_path(__FILE__)
puts "My path #{my_path}"
require "#{File.dirname(File.readlink(my_path))}/glass_stone"
service_name = File.dirname(my_path).split("/").last
service_name =~ /([A-Za-z\.\-]*)-([0-9]*)/
stone_name = $1
port = $2

ENV['LANG'] = 'en_ZA.UTF-8'

puts "Starting up a hyper on port #{port} for #{stone_name}"
stone = GlassStone.new(stone_name)
stone.hyper_service(port).start_fg
